// Import from virtual module (will be generated by Vite plugin)
// @ts-ignore - This module is generated by our Vite plugin at build time
import { posts as initialPosts } from 'virtual:blog-posts';

export interface Post {
  id: number;
  title: string;
  date: string;
  lastmod?: string | false;
  excerpt: string;
  tags: string[];
  slug: string;
  content?: string;
  filename?: string;
}

export const posts: Post[] = initialPosts;

export async function getAllPosts(): Promise<Post[]> {
  return posts;
}

export async function getPostBySlug(slug: string): Promise<Post | undefined> {
  const postFromList = posts.find(p => p.slug === slug);
  
  if (!postFromList) {
    console.error(`Post with slug "${slug}" not found in the pre-loaded list.`);
    return undefined;
  }
  
  if (typeof postFromList.content === 'string') {
    return postFromList;
  } else {
    console.error(`Content for post "${slug}" is missing or not a string from the pre-loaded list. This may indicate an issue with the build process or the virtual module generation.`);
    return {
      ...postFromList,
      content: `Error: Content for post slug "${slug}" was not bundled correctly. Please check the build process.`
    };
  }
} 